esphome:
  name: sidestand-1
  friendly_name: "Sidestand-1"

esp32:
  board: esp32-c3-devkitm-1
  framework: 
    type: arduino
    
bluetooth_proxy:
logger:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Sidestand-1 Fallback Hotspot"
    password: "12345678"

captive_portal:
web_server:
improv_serial:
wled:

# ========== SENSORS ==========
sensor:
  # WiFi Signal Strength
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  # Uptime in seconds
  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "s"
    entity_category: "diagnostic"

  # Free Heap (RAM)
  - platform: template
    name: "Free Heap"
    lambda: 'return (float)ESP.getFreeHeap();'
    unit_of_measurement: "bytes"
    update_interval: 60s
    entity_category: "diagnostic"
    
  # ESP Internal Temperature (supported on ESP32)
  - platform: internal_temperature
    name: "ESP Temperature"
    entity_category: "diagnostic"

# ========== TEXT SENSORS ==========
text_sensor:
  # WiFi Info
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: "mdi:ip-network"
      entity_category: "diagnostic"
    ssid:
      name: "Connected SSID"
      icon: "mdi:wifi"
      entity_category: "diagnostic"
    mac_address:
      name: "MAC Address"
      icon: "mdi:ethernet"
      entity_category: "diagnostic"

# ========== LIGHT ==========

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: GPIO02
    num_leds: 90
    id: strip_light
    name: "Light"
    restore_mode: RESTORE_DEFAULT_OFF
    effects: !include shared/effects.yaml