esphome:
  name: sidestand-2
  friendly_name: "Sidestand-2"

esp8266:
  board: nodemcuv2
  restore_from_flash: true

logger:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 
    minutes: 2
  ap:
    ssid: "Sidestand-2 Fallback Hotspot"
    password: "12345678"

captive_portal:
web_server:
improv_serial:
wled:

# ========== SENSORS ==========
sensor:
  # WiFi Signal Strength
  - platform: wifi_signal
    name: "WiFi Signal (dBm)"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: template
    name: "WiFi Signal"
    unit_of_measurement: "%"
    id: wifi_signal_percent
    update_interval: 60s
    entity_category: "diagnostic"
    icon: "mdi:wifi"
    lambda: |-
      float rssi = id(wifi_signal_db).state;
      float percentage = 2.0 * (rssi + 100.0);
      return std::min(100.0f, std::max(0.0f, percentage));

  # Uptime in seconds
  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "s"
    entity_category: "diagnostic"

  # Free Heap (RAM)
  - platform: template
    name: "Free Heap"
    lambda: 'return (float)ESP.getFreeHeap();'
    unit_of_measurement: "bytes"
    update_interval: 60s
    entity_category: "diagnostic"

  # ESP Internal Temperature (supported on ESP32)
  # - platform: internal_temperature
  #   name: "ESP Temperature"
  #   entity_category: "diagnostic"

# ========== TEXT SENSORS ==========
text_sensor:
  # WiFi Info
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: "mdi:ip-network"
      entity_category: "diagnostic"
    ssid:
      name: "Connected SSID"
      icon: "mdi:wifi"
      entity_category: "diagnostic"
    mac_address:
      name: "MAC Address"
      icon: "mdi:ethernet"
      entity_category: "diagnostic"

# ========== LIGHT ==========

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: GPIO02
    num_leds: 87
    id: strip_light
    name: "Light"
    restore_mode: RESTORE_DEFAULT_OFF
    effects: !include shared/effects.yaml

  - platform: partition
    name: "Segment 1"
    segments: 
      - id: strip_light
        from: 0
        to: 16
  - platform: partition
    name: "Segment 2"
    segments: 
      - id: strip_light
        from: 17
        to: 33
  - platform: partition
    name: "Segment 3"
    segments: 
      - id: strip_light
        from: 34
        to: 50
  - platform: partition
    name: "Segment 4"
    segments: 
      - id: strip_light
        from: 51
        to: 67
  - platform: partition
    name: "Segment 5"
    segments: 
      - id: strip_light
        from: 68
        to: 86
