esphome:
  name: wardrobe
  friendly_name: "Wardrobe"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    
bluetooth_proxy:
  active: true
logger:
  level: DEBUG
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 
    minutes: 2
  ap:
    ssid: "Wardrobe AP"
    password: "12345678"

captive_portal:
web_server:
improv_serial:
debug:
  update_interval: 60s

# ========== SENSORS ==========
sensor:
  - platform: wifi_signal
    name: "WiFi Signal (dBm)"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "s"
    entity_category: "diagnostic"
    
  - platform: internal_temperature
    name: "ESP Temperature"
    entity_category: "diagnostic"

  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    cpu_frequency:
      name: "CPU Frequency"

# ========== TEXT SENSORS ==========
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: "mdi:ip-network"
      entity_category: "diagnostic"
    ssid:
      name: "Connected SSID"
      icon: "mdi:wifi"
      entity_category: "diagnostic"
    mac_address:
      name: "MAC Address"
      icon: "mdi:ethernet"
      entity_category: "diagnostic"

  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
    

# ========== LIGHT ==========

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    chipset: WS2812
    pin: GPIO02
    num_leds: 18
    id: strip_light
    name: "Light"
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - random:
      - pulse:
      - strobe: 
      - flicker:
      - addressable_fireworks:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_scan:
      - addressable_color_wipe:
      - addressable_rainbow: